### ISSUE TITLE
ResizeUploadedImage possible server and client-side Resource Exhaustion Vulnerability

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#26]
The `ResizeUploadedImage` mixin opens attacker supplied images naively
which can lead to a resource exhaustion on the server. Furthermore if
the resize operation fails it saves the image without changes and
possibly serves this imagebomb also to clients causing a resource
exhaustion to the browsers trying to display this image.

```
try:
    image = Image.open(self.image)
except IOError:
    return super(ResizeUploadedImage, self).save(*args, **kwargs)
```

This mixin is used in the AbstractIssuer and the AbstractBadgeClass.

Attached are a PNG and a JPG image that are crafted image bombs to
verify this issue.

Recommendation: use the `Image._decompression_bomb_check()` function
to filter out maliciously crafted images. Or consider upgrading to something >5.0.0: https://pillow.readthedocs.io/en/5.1.x/releasenotes/5.0.0.html?highlight=bomb

**Comment by ottonomy** [comment]
Would be great to get the image examples or links to where to find them online attached to this issue.
