### ISSUE TITLE
Admin can delete protected items on the admin UI

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#30]
The `delete_selected` admin action can be tricked to delete protected objects.

Excerpt from apps/mainsite/admin_actions.py:34

```
if request.POST.get('post'):
```

This action is a fork of the original django implementation, and it
seems it did not apply patches or had this check removed:

```
if request.POST.get('post') and not protected:
```

Protected objects are foreign keys that can be marked as protected in the ORM model:
https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.PROTECT

> Prevent deletion of the referenced object by raising ProtectedError, a subclass of django.db.IntegrityError.

In Openbadges two foreign keys are marked protected:
 - `LocalBadgeClass` sets its Issuer FK as protected.
 - `LocalBadgeInstance` sets its `LocalBadgeClass` to protected.

Excerpts from `apps/composition/models.py`:
```
class LocalBadgeClass(AbstractRemoteImagePreviewMixin, AbstractBadgeClass):
    issuer = models.ForeignKey(LocalIssuer, blank=False, null=False,
                               on_delete=models.PROTECT,
                               related_name="badgeclasses")
```

And `LocalBadgeInstance` which points back to `LocalBadgeClass` as protected:

```
class LocalBadgeInstance(AbstractBadgeInstance):
    # 0.5 BadgeInstances have no notion of a BadgeClass
    badgeclass = models.ForeignKey(LocalBadgeClass, blank=False, null=True,
                                   on_delete=models.PROTECT,
                                   related_name='badgeinstances')
```

Impact: someone with admin rights can delete Issuers that are still
being referenced by other objects putting the database in an
inconsistent state.

Recommendation add the missing check for protected status.

**Comment by ottonomy** [comment]
The specific example from apps/composition/models.py no longer applies in the current version of the code or any version ever deployed by SURFnet, but there are likely similar issues elsewhere. There are a number of fun ways to trigger 500 errors by trying to delete protected resources from the admin. Generally, don't delete things from the admin if they can be deleted via API instead.
