### ISSUE TITLE
JWT signed badges signatures can be forged

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#31]
It is possible to forge the JWT token processed by `def get_badge_instance_from_jwt()`
https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

Neither the implementation or the pyjwt module blacklist the 'none' algorithm and they both process and trust the `alg` parameter passed in the JWT token.

Excerpt from the `apps/verifier/utils.py`:
```
def get_badge_instance_from_jwt(jwt_string):
    (header, payload, signature,) = jwt_string.split('.')
    algorithm = json.loads(b64decode(header))['alg'].upper()

    badge_instance = json.loads(b64decode(payload))
    if badge_instance['verify']['type'] == 'hosted':
        raise ValidationError(
            "A signed badge instance must be validated via public key not hosted.")
    url = badge_instance['verify']['url']
    public_key = _fetch(url)

    try:
        payload = api_jws.decode(jwt_string, public_key,
                                 algorithm=algorithm)
    except InvalidTokenError:
        raise ValidationError(
            "The signed badge instance did not validate against its public key.")

    badge_instance = badge_instance
    return (None, badge_instance)
```

**Comment by ottonomy** [comment]
Please identify which git branch you're looking at. This module hasn't been part of badgr-server for quite some time. Please look at the master or develop branches from the latest release of Badgr-server for CSky's latest code. https://github.com/concentricsky/badgr-server/tree/develop/apps

**Comment by sveeke** [comment]
Hi Nate,

We took the open sourced version from a couple of months ago and froze it for the audit. I still have to add the other issues, then we will filter everything (because there are quite a few issues about our own environment at SURFnet) and make a list for you. If a module has been deprecated in the last couple of months, then of course you can just close the issue as 'fixed' :). At a later point in time we will do another audit (since it's a continuous process), and of course we will then use the then-most-recent version of Badgr.

**Comment by stef** [comment]
we looked at 1be32e66ba301a3b914e1d47185b8c5f0e384b84 which was hosted at https://github.com/SURFnet/edubadges - which disappeared since then.

**Comment by stef** [comment]
btw i just checked the requirements.txt on the concentric sky  repo, and it seems it still uses the pinned version 1.4.0 which is vulnerable to this. just saying, even if apps/verifier/utils.py is indeed gone there.

**Comment by ottonomy** [comment]
Thanks for the details. This requirement is no longer used, and we will take an action to remove the installation from the requirements.txt file.

**Comment by sveeke** [comment]
Fixed then :)
