### ISSUE TITLE
Unhandled Division by Zero

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#32]
The jingo template helper function `divisible_by` in
`apps/mainsite/helpers.py` does not check for the divisor not being
zero and can thus cause an exception.

```
def divisible_by(value, num):
    """Check if a variable is divisible by a number."""
    return value % num == 0
```

Recommendation: This helper function is seemingly not used in the
templates, so it can be removed, or alternatively it can check for
`num!=0`.

**Comment by ottonomy** [comment]
This file and the whole set of templates it supported do not remain in the current version.
