### ISSUE TITLE
untrusted XML parsed with xml.dom.minidom.parseString

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#33]
`apps/bakery/svg_bakery.py` uses xml.dom.minidom.parseString in two locations to parse SVG files, and this makes it vulnerable to _billion laughs_ and _quadratic blowup_ attacks. For more information see https://docs.python.org/3/library/xml.html#xml-vulnerabilities

excerpt from `edubadges/apps/bakery/svg_bakery.py:10`
```
9	
10	    svg_doc = parseString(imageFile.read())
11	    imageFile.close()
```
excerpt from `edubadges/apps/bakery/svg_bakery.py:52`
```
51	def unbake(imageFile):
52	    svg_doc = parseString(imageFile.read())
53	
```

It is recommened to use the defusedxml package instead.

**Comment by ottonomy** [comment]
👍 This bug remains in the code that now is in https://github.com/concentricsky/openbadges-bakery/blob/master/openbadges_bakery/svg_bakery.py
