### ISSUE TITLE
Badge Check can be fooled by forged badges using unicode domain names

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#34]
Currently v0.5 and v1 badges only verify by is this:
```
        if not (domain(self.issuer['origin']) ==
                domain(self.instance_url)):  # TODO: Can come from baked image
```
So it is possible to fake badges with unicode shenanigans, maybe also setting up the domain to return expected responses, but `BadgeCheck` itself does not initiate network connections.

in V1 badgecheck there is also a `check_components_have_same_domain`
but it is not used anywhere, and has a check:
```
        resources = filter(None, [self.badge_instance['verify']['url'],
                                  self.badge_instance['badge'],
                                  self.badge_instance.get('url'),
                                  self.badge_instance.get('id')])
        same_domains = len(set([domain(resource)
                                for resource in resources])) == 1
```
which can be fooled by a badge that has only one of the resources non-None.

Example: `badges.stanford.edu` could be used as a domain, for a human it would be very difficult to realize that the `a` in this domain is a cyrillic lower case `a` letter and not the latin `a`.

Impact: The current implementation would verify this as a valid badge, and a human would easily mistake this as a badge by a prestigious institution.

Recommendation: always convert unicode domains into punycode.

**Comment by ottonomy** [comment]
This django app has been removed, completely rewritten and replaced as the openbadges python library. There may still be bugs in the new system, but it now implements the new Open Badges 2.0 rules for which domains should be trusted (by default and by configuration). See https://openbadgespec.org/#VerificationObject
