### ISSUE TITLE
Pathway*list can be created by anyone with a registered email

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#36]
The POST verb of `PathwayList` seems to allow anyone with a verified email to create new pathways for issuers? The POST verb of `PathwayElementList` also seems to be affected by this?

the corresponding API endpoints are 
 - `/v2/issuers/(?P<issuer_slug>[^/]+)/pathways/`
 - `/v2/issuers/(?P<issuer_slug>[^/]+)/pathways/(?P<pathway_slug>[^/]+)/elements`

It seems the only authorization is needed that the user is logged in and has a confirmed email address.

**Comment by ottonomy** [comment]
This feature is deprecated in recent versions of the code. No pathways may be created. This data model will be removed in future versions of the code.
