### ISSUE TITLE
XSS code injection via Composition Collection share_url

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#37]
In the `collection` app the class `CollectionSerializer` contains a field:

```
share_url = serializers.CharField(read_only=True, max_length=1024)
```
Which despite being an URL it is not validated against the URLField rules.

`CollectionSerializer` is being used by the following writing API endpoints:

 - `CollectionDetail` - PUT `v1/earner/collections/(?P<slug>[-\w]+)$` 
 - `CollectionList` - POST `v1/earner/collections$`

Later this `share_url` member variable is used in `templates/composition/collection_detail_embed.html` in the following way:

```
42:                            <h4><a href="{{collection.share_url}}">{{collection.name}}</a></h4>
95:                    <p class="embed-info">This badge collection verified by <a href="https://badgr.io">Badgr</a>. <a href="{{collection.share_url}}">View details</a>.</p>
```

In both cases `share_url` could be used to inject javascript to the client, by for example specifying `javascript:alert(1)` as the `share_url`.

Recommendation: Change the type of the `share_url` field to a URLField so it gets validated as a URL.

**Comment by ottonomy** [comment]
`read_only=True` means that this value may not be written to by a user. Updates to this serializer have been made, and it now resides in the `backpack` app, but the `read_only` nature of this property remains.

**Comment by sveeke** [comment]
Fixed then.
