### ISSUE TITLE
Development and deprecated modules unconditionally enabled

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#39]
The django settings of the `mainsite` app enable some modules that are either deprecated or only needed for debugging and testing, especially the latter ones can leak information and or provide other facilities to an attacker. They increase the attack-surface unnecessarily.

Excerpt from `apps/mainsite/settings.py`:
```
     jingo
...
     #extradditions for debugging and testing
    'taggit',
    'taggit_serializer',
    'django_extensions',
    'sslserver',
...
    # deprecated packages to remove in v1.2
    'composer',
    'credential_store',
```

A quick check on github shows a lot of open bugs some of which can possibly be abused:
* django-taggit: has 97 open issues on github
* django-taggit-serializer: has 17 open issues on github
* django-rest-swagger: has 91 open issues on github
* jingo, from its README: "Jingo is DEPRECATED"

Recommendation: Remove all unnecessary modules from `settings.py`, or only enable them conditionally in a `settings_local.py`.

**Comment by ottonomy** [comment]
Deprecated badgr-server packages are removed. I don't recognize `taggit` `taggit_serializer`, `django_extensions` or `sslserver`. These appear to be added in this commit https://github.com/concentricsky/badgr-server/commit/5c29311ec4c66248ee302efd881ce04514a689b6 by @hamrt and have never been part of any badgr-server code pushed to SURF's environments.
