### ISSUE TITLE
Python Plugin Version leaked and outdated

### ISSUE THREAD

**Issue by sveeke** [edubadges/audit#6]
The Python Request Plugin used to add badges locates on other webservers appears to be outdated.

The version 2.18.1 that is revealed in the User-Agent header was released on Jun 14, 2017. 

```
omega# nc -nlvp 80
listening on [any] 80 ...
connect to [5.2.67.184] from (UNKNOWN) [145.101.112.185] 49920
GET / HTTP/1.1
Host: omega.svits.nl
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: application/ld+json, application/json, image/png, image/svg+xml
User-Agent: python-requests/2.18.1
```

**Comment by ottonomy** [comment]
Only one minor release behind... We'll add this to our list of planned upgrades, probably will be a one liner.

**Comment by sveeke** [comment]
I close it then.
